"""Use-case contracts independent of transports and concrete storage."""

from workaholic.application.bootstrap import BootstrapApplication
from workaholic.application.commands import (
    BootstrapLocalProjectInput,
    BootstrapMutation,
    CreateProjectInput,
    CreateTaskInput,
    GetLocalStatus,
    GetProjectByKey,
    GetTask,
    ListInstanceTasks,
    ListProjects,
    ListTasks,
    ProjectCreationMutation,
    TaskCreationMutation,
)
from workaholic.application.errors import (
    ApplicationError,
    ApplicationErrorCode,
    ExitCategory,
    IdempotencyConflictError,
    InvalidInputError,
    NotInitializedError,
    PermissionDeniedError,
    ProfileInvalidError,
    ProfileNotFoundError,
    ProfileUnsupportedError,
    ProjectKeyConflictError,
    ProjectNotFoundError,
    TaskNotFoundError,
    WorkspaceBindingConflictError,
)
from workaholic.application.ports import (
    BootstrapRepository,
    Clock,
    IdentifierFactory,
    ProjectRepository,
    QueryRepository,
    TaskRepository,
    WorkaholicRepository,
)
from workaholic.application.projects import ProjectApplication
from workaholic.application.queries import QueryApplication
from workaholic.application.results import (
    BootstrapResult,
    ContextResult,
    ProjectCreationResult,
    StatusResult,
    TaskPage,
)
from workaholic.application.tasks import TaskApplication

__all__ = [
    "ApplicationError",
    "ApplicationErrorCode",
    "BootstrapApplication",
    "BootstrapLocalProjectInput",
    "BootstrapMutation",
    "BootstrapRepository",
    "BootstrapResult",
    "Clock",
    "ContextResult",
    "CreateProjectInput",
    "CreateTaskInput",
    "ExitCategory",
    "GetLocalStatus",
    "GetProjectByKey",
    "GetTask",
    "IdempotencyConflictError",
    "IdentifierFactory",
    "InvalidInputError",
    "ListInstanceTasks",
    "ListProjects",
    "ListTasks",
    "NotInitializedError",
    "PermissionDeniedError",
    "ProfileInvalidError",
    "ProfileNotFoundError",
    "ProfileUnsupportedError",
    "ProjectApplication",
    "ProjectCreationMutation",
    "ProjectCreationResult",
    "ProjectKeyConflictError",
    "ProjectNotFoundError",
    "ProjectRepository",
    "QueryApplication",
    "QueryRepository",
    "StatusResult",
    "TaskApplication",
    "TaskCreationMutation",
    "TaskNotFoundError",
    "TaskPage",
    "TaskRepository",
    "WorkaholicRepository",
    "WorkspaceBindingConflictError",
]
