"""Safe internal failures raised by authentication primitives."""

from __future__ import annotations


class AuthenticationPrimitiveError(ValueError):
    """Base failure for malformed credentials and unsafe entropy sources."""


class TokenFormatError(AuthenticationPrimitiveError):
    """Raised when a raw Token or digest is not canonical."""

    def __init__(self) -> None:
        """Initialize a stable error that never embeds credential material."""
        super().__init__("The Token is not in canonical Workaholic format.")


class TokenGenerationError(AuthenticationPrimitiveError):
    """Raised when an injected entropy source violates its contract."""

    def __init__(self) -> None:
        """Initialize a stable error without exposing generated bytes."""
        super().__init__("Secure Token generation failed.")
